# Generated by Django 5.0.2 on 2024-08-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='email',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='metros_cubiertos',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='metros_totales',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ubicacion',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
