# Generated by Django 5.0.2 on 2024-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasador', '0002_remove_propiedad_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('m2', models.FloatField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Propiedad',
        ),
    ]
